FROM python:3.11.1
RUN python3 -m pip install --upgrade pip
RUN pip cache purge
WORKDIR /app
RUN git clone https://github.com/Rayanlaffi1/apipapyrus.git .
RUN pip install -r requirements.txt
EXPOSE 5000
# CMD ["python", "./fonctions/initkeycloak.py"]
CMD ["python", "api.py"]
